### ISSUE TITLE
polymer 1 rc14 - error when access to a polymer_element attribute

### ISSUE THREAD

**Issue by lejard-h** [dart-lang/polymer_elements#120]
I am updating an app to polymer 1.0.0-rc14.

This code was working before this version:

```
PaperDrawerPanel get drawer => $['drawerPanel'];
@reflectable
pageChanged(String value, String old) {
    ...
    drawer?.drawerWidth = "0";
    ...
}
```

Now I am having this error.

```
Unhandled exception:
NoSuchMethodError: method not found: 'drawerWidth='
Receiver: Instance of 'JsObjectImpl'
Arguments: ["0"]
#0      JsObject.noSuchMethod.throwError (dart:js:1084)
#1      JsObject.noSuchMethod (dart:js:1111)
#2      RootElement.pageChanged (package:walletek_app_web/elements/root_element/root_element.dart:38:17)
#3      Function._apply (dart:core-patch/function_patch.dart:7)
#4      Function.apply (dart:core-patch/function_patch.dart:28)
#5      _InstanceMirrorImpl.invoke (package:reflectable/src/reflectable_transformer_based.dart:252:21)
#6      addDeclarationToPrototype.<anonymous closure> (package:polymer/src/common/declarations.dart:134:35)
#7      JsFunction._apply (dart:js:1178)
#8      JsFunction.apply (dart:js:1176)
#9      HtmlElement&PolymerMixin&PolymerBase.notifyPath (package:polymer_interop/src/polymer_base.dart:232:28)
#10     PolymerElementPropertyNotifier.notifyPath (package:polymer_autonotify/polymer_autonotify.dart:340:33)
#11     PropertyNotifier&HasChildrenMixin&HasChildrenReflectiveMixin.observe.<anonymous closure>.<anonymous closure> (package:polymer_autonotify/polymer_autonotify.dart:223:9)
#12     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
#13     PropertyNotifier&HasChildrenMixin&HasChildrenReflectiveMixin.observe.<anonymous closure> (package:polymer_autonotify/polymer_autonotify.dart:220:17)
#14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1087)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#17     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:381)
#18     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:256)
#19     PolymerElement&AutonotifyBehavior&JsProxy&ChangeNotifier.deliverChanges (package:observe/src/change_notifier.dart:49:16)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#21     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#22     _ScheduleImmediateHelper._handleMutation (dart:html:49298)
#23     MutationObserver._create.<anonymous closure> (dart:html:27545)
#0      JsFunction._apply (dart:js:1178)
#1      JsFunction.apply (dart:js:1176)
#2      HtmlElement&PolymerMixin&PolymerBase.notifyPath (package:polymer_interop/src/polymer_base.dart:232:28)
#3      PolymerElementPropertyNotifier.notifyPath (package:polymer_autonotify/polymer_autonotify.dart:340:33)
#4      PropertyNotifier&HasChildrenMixin&HasChildrenReflectiveMixin.observe.<anonymous closure>.<anonymous closure> (package:polymer_autonotify/polymer_autonotify.dart:223:9)
#5      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
#6      PropertyNotifier&HasChildrenMixin&HasChildrenReflectiveMixin.observe.<anonymous closure> (package:polymer_autonotify/polymer_autonotify.dart:220:17)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1087)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#10     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:381)
#11     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:256)
#12     PolymerElement&AutonotifyBehavior&JsProxy&ChangeNotifier.deliverChanges (package:observe/src/change_notifier.dart:49:16)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#14     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#15     _ScheduleImmediateHelper._handleMutation (dart:html:49298)
#16     MutationObserver._create.<anonymous closure> (dart:html:27545)
```

I tried to access to other attributes of other elements it's the same.

**Comment by jakemac53** [comment]
I noticed you are using `PolymerElementPropertyNotifier` which I think is from the `polymer_autonotify` package? It seems to me that that is actually causing the issue although its hard to tell for sure. This isn't a general systemic issue cause all the polymer_elements tests are passing.

**Comment by lejard-h** [comment]
Okay maybe I missed or I didn't understand something here.
I tried without `polymer_autonotify` it's still the same
My application look like this

my_app_library.dart

```
library my_app;

export "my_elements.dart";
export "material.dart"
```

my_elements.dart

```
library my_app.elements;

export "root_element.dart";
```

material.dart

```
library my_app.material;

export "package:polymer_elements/paper_drawer_panel";
```

And this is the root-element

```
import "package:my_app/my_app_library.dart";

@PolymerRegister("root-element")
class RootElement extends PolymerElement {
  RootElement.created() : super.created();

  PaperDrawerPanel get drawer => $['drawerPanel'];

  ready() {
   print(drawer.drawerWidth);
  }
}
```

I have no error if I import directly in the root-element the material library. Why ?

```
import "package:my_app/my_app_library.dart";
import "package:my_app/material.dart";
```

**Comment by jakemac53** [comment]
So the issue here is actually the order in which things are being registered. In general, the best way to avoid this type of problem is to not use the `export` pattern to bundle up large number of elements. If you do that you need to make sure that you put them in the right order.

Specifically in your case it looks like the way the exports were set up, `root_element.dart` would get loaded (and registered) before `material.dart` (and thus `paper-drawer-panel`). You could also solve the issue by just changing the order of your exports in the `my_app_library.dart` file to make the `material.dart` file come first.
